### PR TITLE
Changing import of glue to pycbc_glue

### PR DESCRIPTION
**Pull request by a-r-williamson**
Hi @spxiwh,

I believe we need to change this import to keep in line with `pycbc`, is that correct?

Andrew

### CODE REVIEW

**Comment by spxiwh** [comment]
Actually I wouldn't recommend this change. I'm trying to push pycbc back toward using the proper glue in the future, and segments will be one of the first things to be moved from `pycbc_glue` to `glue`. pycbc currently depends on both pycbc_glue *and* glue, and this will probably continue for some time, with pycbc_glue having modules removed from it as they become unnecessary.

**Comment by spxiwh** [comment]
For any of the ligolw routines you should continue to use `pycbc_glue`. But for segments, or authentication modules stick with normal glue.

**Comment by spxiwh** [comment]
I'll close this now, but feel free to reopen if you disagree.

**Comment by a-r-williamson** [comment]
@spxiwh ok, I agree in principle with your reasoning, but here's the issue:

In the process of generating a `PyGRB` workflow we generate `coh_PTF_inspiral` node [here](https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/jobsetup.py#L348-L351), which leads us to the job class stuff in `pycbc-pylal`, specifically the generation of segments [here](https://github.com/ligo-cbc/pycbc-pylal/blob/master/pylal/legacy_ihope.py#L236-L237) and [here](https://github.com/ligo-cbc/pycbc-pylal/blob/master/pylal/legacy_ihope.py#L316), which leads to an error when these are passed to `pycbc` routines expecting `pylal_glue` segments, specifically [here](https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/core.py#L793-L796).

The error message we first run into is:

```
  File "/mnt/qfs3/andrew.williamson/pycbc-devel-env/src/pycbc/pycbc/workflow/jobsetup.py", line 351, in multi_ifo_coherent_job_setup
    ipn_file=ipn_sky_points)
  File "/mnt/qfs3/andrew.williamson/pycbc-devel-env/src/pycbc-pylal/pylal/legacy_ihope.py", line 281, in create_node
    tags=tags, store_file=self.retain_files)
  File "/mnt/qfs3/andrew.williamson/pycbc-devel-env/src/pycbc/pycbc/workflow/core.py", line 796, in new_output_file_opt
    use_tmp_subdirs=use_tmp_subdirs)
  File "/mnt/qfs3/andrew.williamson/pycbc-devel-env/src/pycbc/pycbc/workflow/core.py", line 959, in __init__
    raise ValueError(err)
ValueError: segs input must be either glue.segments.segment or segments.segmentlist. Got <type 'glue.__segments.segment'>.
```

So it's the fact that the main `pycbc` stuff is using the `pycbc_glue` import for segments that suggests to me we should keep consistency here. Or would you suggest a different change?

**Comment by spxiwh** [comment]
Damn, these types should be compatible. Okay, feel free to push if this helps to get things moving. Be aware though that @duncanmmacleod was poking me earlier about continuing to retire pycbc-glue. So expect a pull request soon to flip *all* `import pycbc_glue.segment` statements to `import glue.segment`. Maybe we just revert this after that goes in? You have write access here, so feel free to self-approve changes of this nature anywhere in pycbc-pylal.

**Comment by a-r-williamson** [comment]
Absolutely, we should flip this back at the same time as those changes are made. Thanks.

**Pull request merged**
