### PR TITLE
Fix trig_combiner bug when 1 IFO

### PR DESCRIPTION
**Pull request by a-r-williamson**
Hi Steve,

This fixes a bug that came up when running on 1 IFO data. Can you take a look then merge if happy?

Cheers,
Andrew

### CODE REVIEW

**Comment by spxiwh** [comment]
@a-r-williamson can you explain what bug this is fixing?

**Comment by a-r-williamson** [comment]
@spxiwh when running on single IFO data the tables such as timeSlideTable were undefined at the point when they are added to the output document. This was introduced accidentally when fixing the issue with short time slide triggers contaminating our FAP values.

**Comment by sfairhur** [comment]
@a-r-williamson if the docs like timeSlideTable, etc are undefined when they're being added to the output doc, wouldn't it be better to not add them?  I guess that would require teaching the downstream code not to worry if they're not available.

**Comment by a-r-williamson** [comment]
@sfairhur I mean that, for example, in [this line] (https://github.com/ligo-cbc/pycbc-pylal/pull/19/files#diff-df80b3d85dc32eb52a687d70a51c7a05R379) we had not set timeSlideTable to anything for the single IFO case because those lines had been removed in the last change. I understand that the table will just contain the zero lag slide definition. Is there a strong reason not to continue to do this?

**Comment by sfairhur** [comment]
OK, makes sense.  I've merged the code

**Pull request merged**
